# Generated by Django 4.1.1 on 2022-10-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_libro_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, upload_to='portada'),
        ),
    ]
